### ISSUE TITLE
Is there a board count limit?

### ISSUE THREAD

**Issue by pstaszko** [rjmunro/pyLaunchpad#5]
Quick question, I can add details if needed. I have rigged up a system using 6 launchpad mk3 minis with 6 python scripts running on the same machine using this library. I recently tried to add 2 more and it's not going well. Off the bat, would there be an obvious reason why I could have 6, but not 7 or 8 at the same time (with a separate python script instance  per board)?

**Comment by pstaszko** [comment]
Scratch that, I was mistaken. I have 8 boards working now.
![IMG_20220215_121952016_HDR](https://user-images.githubusercontent.com/14144789/154124983-05b06fd9-6d8e-4575-96c1-5b9d05463860.jpg)

**Comment by rjmunro** [comment]
There are no limits in the python code. There may be some limiting factor somewhere upstream but I'm not aware of one.

Cool looking project, by the way :-) I'm glad people are still finding this useful.
